<a href="https://colab.research.google.com/github/ssafreed/pytorch/blob/main/pytoctch_Basic_operations_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

LISTS

In [2]:
my_list = [1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


Numpy Arrays

In [3]:
np1 = np.random.rand(3,4)
np1

array([[0.65995673, 0.35744342, 0.47289441, 0.0462412 ],
       [0.66616339, 0.82168491, 0.81017062, 0.59458651],
       [0.17373159, 0.2328973 , 0.43879741, 0.45830783]])

In [4]:
np1.dtype

dtype('float64')

TENSOR

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6600, 0.3574, 0.4729, 0.0462],
        [0.6662, 0.8217, 0.8102, 0.5946],
        [0.1737, 0.2329, 0.4388, 0.4583]], dtype=torch.float64)

Tensor Operations

In [15]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#Reshape and View
my_torch1 = my_torch.reshape(2,5)
my_torch1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
#Reshape if we dont know the no of items using -1
my_torch2 = my_torch.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
my_torch3 = my_torch.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [25]:
# with reshape and view they will update
my_torch4 = torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
my_torch5 = my_torch4.reshape(2,5)
my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
my_torch4[1] = 4141
my_torch4

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [28]:
my_torch5

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [29]:
# Slices
my_torch6 = torch.arange(10)
my_torch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# Grab a specific item
my_torch6[7]

tensor(7)

In [32]:
# Grab a Slice
my_torch7 = my_torch6.reshape(5,2)
my_torch7

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [33]:
my_torch7[:,1]

tensor([1, 3, 5, 7, 9])

In [34]:
my_torch7[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

TENSOR MATH OPERATIONS

In [52]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [36]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [37]:
# Addition longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [38]:
# Subtration
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [39]:
# Sub longhand
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

In [40]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [41]:
# Multiplication longhand
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [42]:
# Division
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [43]:
# Division Longhand
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [44]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [45]:
# Remainder Long hand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [46]:
# Exponets / Power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [49]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [53]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])